"""add_portfolio_json

Revision ID: 21902ab49ece
Revises: 68a6b68cf7ab
Create Date: 2026-01-22 23:44:11.124484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21902ab49ece'
down_revision: Union[str, None] = '68a6b68cf7ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_stats', sa.Column('portfolio_json', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_stats', 'portfolio_json')
    # ### end Alembic commands ###
