"""add_social_fields_to_user

Revision ID: 50910c2cf988
Revises: 
Create Date: 2026-01-22 21:19:22.391965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50910c2cf988'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('linkedin_username', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('twitter_username', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('website', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('location', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'location')
    op.drop_column('users', 'website')
    op.drop_column('users', 'twitter_username')
    op.drop_column('users', 'linkedin_username')
    # ### end Alembic commands ###
