"""add_popular_repo_contributions

Revision ID: 68a6b68cf7ab
Revises: d624d6037d8b
Create Date: 2026-01-22 23:21:28.286764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68a6b68cf7ab'
down_revision: Union[str, None] = 'd624d6037d8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_stats', sa.Column('popular_repo_contributions_json', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_stats', 'popular_repo_contributions_json')
    # ### end Alembic commands ###
