"""add_stackoverflow_devto_hashnode_fields

Revision ID: d624d6037d8b
Revises: 50910c2cf988
Create Date: 2026-01-22 23:06:51.148059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd624d6037d8b'
down_revision: Union[str, None] = '50910c2cf988'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_stats', sa.Column('stackoverflow_json', sa.JSON(), nullable=True))
    op.add_column('user_stats', sa.Column('devto_json', sa.JSON(), nullable=True))
    op.add_column('user_stats', sa.Column('hashnode_json', sa.JSON(), nullable=True))
    op.add_column('user_stats', sa.Column('verified_skills_json', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('stackoverflow_user_id', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('devto_username', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('hashnode_username', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hashnode_username')
    op.drop_column('users', 'devto_username')
    op.drop_column('users', 'stackoverflow_user_id')
    op.drop_column('user_stats', 'verified_skills_json')
    op.drop_column('user_stats', 'hashnode_json')
    op.drop_column('user_stats', 'devto_json')
    op.drop_column('user_stats', 'stackoverflow_json')
    # ### end Alembic commands ###
